"""remove pricing and tax fields from product

Revision ID: 9574682f580c
Revises: 87797440434f
Create Date: 2026-09-05 15:04:41.016409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9574682f580c'
down_revision: Union[str, Sequence[str], None] = '87797440434f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'currency')
    op.drop_column('products', 'base_price')
    op.drop_column('products', 'tax_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('tax_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('base_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
